config/routes.rb
Rails.application.routes.draw do

  root 'todos#index'

  resources :imports
  resources :todos
  devise_for :users

end

app/models/import.rb
class Import < ActiveRecord::Base

  belongs_to :user
  has_many :todos

  def file=(file)
    SmarterCSV.process(file.path) do |array|
      Todo.create( array.first.merge({import_id: self.id}) )
    end
  end

end

# == Schema Information
#
# Table name: imports
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

app/models/todo.rb
class Todo < ActiveRecord::Base

  belongs_to :import

end

# == Schema Information
#
# Table name: todos
#
#  id          :integer          not null, primary key
#  content     :string(255)
#  due_at      :date
#  private     :boolean
#  trashed     :boolean
#  creator_id  :integer
#  assignee_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#  import_id   :integer
#  completed   :boolean
#

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :imports
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!

  def index
  end

end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_import, only: [:show, :edit, :update, :destroy]

  # GET /imports
  # GET /imports.json
  def index
    @imports = Import.all
  end

  # GET /imports/1
  # GET /imports/1.json
  def show
  end

  # GET /imports/new
  def new
    @import = Import.new
  end

  # GET /imports/1/edit
  def edit
  end

  # POST /imports
  # POST /imports.json
  def create
    @import = current_user.imports.new(import_params)

    respond_to do |format|
      if @import.save
        @import.file=(params[:import][:file])
        format.html { redirect_to @import, notice: 'Import was successfully created.' }
        format.json { render :show, status: :created, location: @import }
      else
        format.html { render :new }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imports/1
  # PATCH/PUT /imports/1.json
  def update
    respond_to do |format|
      if @import.update(import_params)
        format.html { redirect_to @import, notice: 'Import was successfully updated.' }
        format.json { render :show, status: :ok, location: @import }
      else
        format.html { render :edit }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imports/1
  # DELETE /imports/1.json
  def destroy
    @import.destroy
    respond_to do |format|
      format.html { redirect_to imports_url, notice: 'Import was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Import.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def import_params
      params.require(:import).permit(:title)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, flash: { success: 'Todo was successfully created.' } }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo,  flash: { success: 'Todo was successfully updated.' } }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:content, :due_at, :private, :trashed, :creator_id, :assignee_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>

app/views/imports/_form.html.erb
<%= form_for(@import) do |f| %>
  <% if @import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
      <% @import.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/imports/edit.html.erb
<h1>Editing import</h1>

<%= render 'form' %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

app/views/imports/index.html.erb
<h1>Listing imports</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Imported by</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @imports.each do |import| %>
      <tr>
        <td><%= import.title %></td>
        <td><%= import.user.try(:email) %></td>
        <td><%= link_to 'Show', import %>
        | <%= link_to 'Destroy', import, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Import', new_import_path %>

app/views/imports/new.html.erb
<h1>New import</h1>

<%= form_for(@import) do |f| %>
  <% if @import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
      <% @import.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: "Give this import a name so you can refer back to it in the future" %>
  </div>

  <div class="field">
    <label>CSV File</label> <%= link_to 'example', '/csv_file.csv' %><br>
    <code>content,due_at,private</code><br/>
    <%= f.file_field :file %>
  </div>

  <div class="actions">
    <%= f.submit "Import" %>
  </div>
<% end %>

<%= link_to 'Back', imports_path %>

app/views/imports/show.html.erb
<h2><%= @import.title %></h2>

<hr/>

<h5>Todos Imported:</h5>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Due at</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @import.todos.each do |todo| %>
      <tr>
        <td><%= todo.content %></td>
        <td><%= todo.due_at %></td>
        <td><%= link_to 'Details', todo %>
        | <%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_import_path(@import) %> |
<%= link_to 'Back', imports_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sandbox018StarterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id='main' class='<%= controller_name %> <%= action_name %>'>

  <%= render 'shared/nav' %>
  <%= render 'shared/flash' %>

  <section id='content'>
    <%= yield %>
  </section>

</div>

</body>
</html>

app/views/shared/_flash.html.erb
<section class="flash">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, class: "flash-#{name}" do %>
      <%= msg %>
      <a aria-hidden="true" class="close-symbol fa fa-times" data-dismiss="alert"></a>
    <% end %>
  <% end %>
</section>

app/views/shared/_nav.html.erb
<header class="navigation">
  <div class="navigation-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="">
    </a>
    <a href="" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <div class="nav">
      <ul id="navigation-menu">
        <li class="nav-link"><%= link_to 'Todos', todos_path %></a></li>
        <li class="nav-link"><%= link_to 'Imports', imports_path %></a></li>
        <li class="nav-link"><%= link_to 'Import Todos', new_import_path %></a></li>
      </ul>
    </div>
    <div class="navigation-tools">
      <ul>
        <% if user_signed_in? %>
          <li class="nav-link"><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
        <% else %>
          <li class="nav-link"><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li class="nav-link"><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :due_at %><br/>
    <%= f.date_select :due_at %>
  </div>
  <div class="field">
    <%= f.check_box :private %><%= f.label :private %>
  </div>
  <div class="field">
    <%= f.check_box :trashed %><%= f.label :trashed %>
  </div>
  <div class="field">
    <%= f.label :creator_id %>
    <%= f.number_field :creator_id %>
  </div>
  <div class="field">
    <%= f.label :assignee_id %>
    <%= f.number_field :assignee_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<tr>
  <td><%= todo.content %></td>
  <td><%= todo.due_at %></td>
  <td><%= todo.private %></td>
  <td><%= todo.trashed %></td>
  <td><%= todo.creator_id %></td>
  <td><%= todo.assignee_id %></td>
  <td><%= link_to 'Show', todo %>
  | <%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/todos/_todos.html.erb
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Due at</th>
      <th>Private</th>
      <th>Trashed</th>
      <th>Creator</th>
      <th>Assignee</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render todo, collection: @todos %>
  </tbody>
</table>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Due at</th>
      <th>Private</th>
      <th>Trashed</th>
      <th>Creator</th>
      <th>Assignee</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render @todos %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>

<p>
  <strong>Due at:</strong>
  <%= @todo.due_at %>
</p>

<p>
  <strong>Private:</strong>
  <%= @todo.private %>
</p>

<p>
  <strong>Trashed:</strong>
  <%= @todo.trashed %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @todo.creator_id %>
</p>

<p>
  <strong>Assignee:</strong>
  <%= @todo.assignee_id %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>